# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Everyday Programming
title_separator: "|"
email: peter@thepetersmith.com
description: >- # this means to ignore newlines until "baseurl:"
  Programming isn’t for math whizzes and geeks. It’s for every day
  people. Hoping to take the fear out of programming, and show the love,
  the art and the fun that’s intrinsic to it.
twitter_username: petersmithca
github_username: psmithca
minimal_mistakes_skin: air
search: true
url: "https://psmithca.github.io"
baseurl: "/psmithca"
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
repository: "psmithca/psmithca"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Peter Smith"
  avatar : "/assets/images/bio-photo.png"
  bio    : ""
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UC3Nw7ADBfqRU7EY2Gkwp3VA"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Every1Codes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/psmithca"
    - label: "Blog"
      icon: "fab fa-fw fa-wordpress"
      url: "https://thepetersmith.com/blog"

footer:
  links:
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UC3Nw7ADBfqRU7EY2Gkwp3VA"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Every1Codes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/psmithca"
    - label: "Blog"
      icon: "fab fa-fw fa-wordpress"
      url: "https://thepetersmith.com/blog"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
